### ISSUE TITLE
help setting

### ISSUE THREAD

**Issue by NyxKazuya** [amartinsec/BadBird-C2#1]
What line do I have to modify in "c2Server.py", and in "implant.py".
 and to generate the token?

https://i.imgur.com/CFoqyLZ.png

**Comment by amartinsec** [comment]
The only lines you should have to change is `key=b'<insert 32 length key>'` for the encryption key to be used (currently line 56 in c2server.py and 39 in implant.py. It will work by leaving it as default, but if someone can access the management page, they would be able to decrypt the results.

In your screenshot, it looks like you are creating a token through the webUI. This isn't needed and currently not supported. Running `create-token` will fetch a new token and output the management URL that can be entered to the default implant.py once running. If running `create-implant`, a token will be fetched and that token will be added to the generated implant.
